spring:
    application:
        name: jf-cloud-eureka
#    security:
#      user:
#        name: admin
#        password: admin
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/